name: Apply resources Azure

on:
  workflow_dispatch:
    inputs:
      localisation:
        description: 'Localisation de la ressource'
        required: true
      nomRessource:
        description: 'Nom de la ressource'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Import existing resources
        working-directory: ./terraform
        run: |
          terraform import azurerm_resource_group.existing_rg /subscriptions/319819ff-ed9b-4c33-a3d3-d7833a1a5a54/resourceGroups/${{ github.event.inputs.nomRessource }}

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan \
            -var="localisation=${{ github.event.inputs.localisation }}" \
            -var="nomRessource=${{ github.event.inputs.nomRessource }}"

      - name: Deploy if approved
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve tfplan