name: Destroy resources Azure

on:
  workflow_dispatch:
    inputs:
      nomRessource:
        description: 'Nom de la ressource'
        required: true
      localisation:
        description: 'Localisation de la ressource'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform 
        run: terraform init -reconfigure -backend-config="key=${{ github.event.inputs.nomRessource }}"
      
      - name: Destroy if approved
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve \
          -var="localisation=${{ github.event.inputs.localisation }}" \
          -var="nomRessource=${{ github.event.inputs.nomRessource }}" \
          -var="key=${{ github.event.inputs.nomRessource }}"
